### ISSUE TITLE
Right margin (columns) value is not the actual value in the editor

### ISSUE THREAD

**Issue by lgyjg** [ciscorucinski/ChroMATERIAL#27]
When I changed the fonts size in `Editor -> Colors & Fonts -> Font -> Primary font`, I found the Right margin columns is not in the right place, I tried to change the value to 170, the line's persition is match the actual position of 100th line. 

Please resolve this problem if nessasary. Thanks.

**Comment by ciscorucinski** [comment]
I just tested for this, and I am not able to reproduce the behavior you are talking about. 

I tested this with and without my color scheme, with and without a font change, and I didn't see any difference in the position of the right margin position.

I would be surprised if this issue is actually due to my color scheme. Being a color scheme, I am only able to effect the colors and the font. I cannot move items around.

**Please check these items:**
 1. `Editor > Code Style > Right Margin` --> is it set to `100`?
 2. `Editor > Code Style > Java > Wrapping & Braces > Right Margin` --> is it set to `DEFAULT` or `100`?
 3. On the line that you are measuring the column position, check that there is no Yellow text on that line. That might indicate collapsed text that is automatically done by the IDE. 

You can modify number 1 and 2 to suit your needs. 

_If I am mistaken by what you are talking about, then please provide more detail and pictures (current and expected)_

**Comment by lgyjg** [comment]
Hi ciscorucinski:
Thanks for your reply, I forgot tell you that I use the [Making Android Studio pretty 's ](https://meedamian.com/post/deuglifying-android-studio/?hi) solution. I changed the GUI theme with Material Theme UI, and then, use the ChroMATERIAL for Color Scheme.
I checked your provided items, They are all right.   You can see my config as the follow pictures:

![1](https://cloud.githubusercontent.com/assets/7949357/24362720/2ff2c216-1340-11e7-8901-095848cd6ae2.jpg)
You can see the Right margin columns line at 56th columns instead of 100th.
![2](https://cloud.githubusercontent.com/assets/7949357/24362879/b7fd20c0-1340-11e7-9df1-59e3d647bd89.jpg)
This picture show I changed my fonts size with 24.
![3](https://cloud.githubusercontent.com/assets/7949357/24362779/58a55eee-1340-11e7-9904-35e93c80ddb0.jpg)
![4](https://cloud.githubusercontent.com/assets/7949357/24362780/58d62aa6-1340-11e7-8933-a459d61d487d.jpg)

Maybe it is the Material Theme UI's issue. if you can not reproduce, I can close this issue. 
Thank you.

**Comment by ciscorucinski** [comment]
Can you try to disable my color scheme to see if the issue still persists? Also, you can try to disable Material Theme UI temporarily to see if the issue persists or not.

I currently use both my color scheme and Material Theme UI, but I cannot reproduce what you are seeing.

**Comment by lgyjg** [comment]
I am sorry too late responsing , maybe it is other reasons cause this problem, I close this issue temporarily, if I find the reason I will told you and reopen this issue. 
thx
